################################################################
#                                                              #
#          █▀▀ █▀█ █▀▄▀█ █▀▄▀█ ▄▀█ █▄ █ █▀▄ █▀ ▄█▄             #
#          █▄▄ █▄█ █ ▀ █ █ ▀ █ █▀█ █ ▀█ █▄▀ ▄█  ▀              #
#                                                              #
#█▄▄ █▄█   █▀▀ █▀▄ ▄▀█ █   █ ▄▀█   ▄▀ █▀█ █▀▀ █ █▀█ ▀█▀ █ █▀▄▀█#
#█▄█  █    █▄█ █▄▀ █▀█ █▄▄ █ █▀█ ▄▀   █▄█ █▀  █ █▀▄  █  █ █ ▀ █#
#                                                              #
################################################################

PREFIX: "&7Commands&b+ &f» "
ban-command: "ban {player} no alts online!"
kick-command: "kick {player} no alts online!"

#If you want to disable the welcome message just change to true.
disable_welcome_message: false

#If you want to disable the sounds just change to true.
disable_sounds: false

chat:
   locked: false
   clear-template:
      - "&5&l&m----------------------------"
      - ""
      - "&d&lChat has been cleared"
      - ""
      - "&5&l&m----------------------------"

punishments-lang:
    tempban-template:
       - "&cYou are temporarily banned from &6yourserver.example&c."
       - ""
       - "&7Expiry: &f%time%"
       - ""
       - "&7Reason: &f%reason%"
       - ""
       - "&7If you feel this punishment is unjustified, fill out a support ticket at &6www.yourwebsite.com."
       
    ban-template:
       - "&cYou are permanently banned from &6yourserver.example&c."
       - ""
       - "&7Reason: &f%reason%"
       - ""
       - "&7If you feel this punishment is unjustified, fill out a support ticket at &6www.yourwebsite.com."
        
    kick-template:
        - "&cYou have been kicked from &6yourserver.example&c."
        - ""
        - "&7Reason: &f%reason%"


report-lang:
  staff-template:
    - "&7&m-----&6&lNew Report&7&m-----"
    - "&7Reported: &c%REPORTED%"
    - "&7Reporter: &a%REPORTER%"
    - "&7Type: &e%TYPE%"
    - "&7Status: &e%STATUS%"
    - "&7&m---------------------"

# The maximum reasons is 27 and all the reasons title need to be like this for example 'Reason1 Reason2 etc..'
reasons:
  fly-hacks:
    display-name: "Fly"
    lore:
    - "The player is flying&7."
    icon: FEATHER
  speed-hacks:
    display-name: "Speed"
    lore:
    - "The player is moving too quick&7."
    icon: CHAINMAIL_LEGGINGS
  force-field-hack:
    display-name: "ForceField"
    lore:
    - "The player is hitting players/entities abnormally&7."
    icon: IRON_SWORD
  reach-hacks:
    display-name: "Reach"
    lore:
    - "The player is hitting players/entities from far away&7."
    icon: STICK
  rapidbowshot-hack:
    display-name: "RapidBowShot"
    lore:
    - "The player is shooting arrows too quickly&7."
    icon: BOW
  noknockback-hack:
    display-name: "NoKnockback"
    lore:
    - "The player does not take any knock back&7."
    icon: FISHING_ROD
  grief:
    display-name: "Grief"
    lore:
    - "The player griefed one of my constructions&7."
    icon: TNT
  chat-insults:
    display-name: "Insults"
    lore:
    - "The player is disrespectful&7."
    icon: OAK_SIGN