################################################################
#                                                              #
#          █▀▀ █▀█ █▀▄▀█ █▀▄▀█ ▄▀█ █▄ █ █▀▄ █▀ ▄█▄             #
#          █▄▄ █▄█ █ ▀ █ █ ▀ █ █▀█ █ ▀█ █▄▀ ▄█  ▀              #
#                                                              #
#█▄▄ █▄█   █▀▀ █▀▄ ▄▀█ █   █ ▄▀█   ▄▀ █▀█ █▀▀ █ █▀█ ▀█▀ █ █▀▄▀█#
#█▄█  █    █▄█ █▄▀ █▀█ █▄▄ █ █▀█ ▄▀   █▄█ █▀  █ █▀▄  █  █ █ ▀ █#
#                                                              #
################################################################

version: 2.1
plugin-prefix: "&7Commands&b+ &f» "
ban-command: "ban {player} no alts online!"
kick-command: "kick {player} no alts online!"

#If you want to disable the welcome message just change to true.
disable_welcome_message: false

#If you want to disable the sounds just change to true.
disable_sounds: false

#-------------------------------------------------------------------------------------------------#
# Currently we use only 4 types of database drivers: MYSQL, MARIADB, MONGODB, SQLITE & FLATFILE.  #
# MYSQL =    A Query system used mostly for consistent data saving, uses lightweight traffic      #
#            and does not tank performance much, it can be used as default a preference.          #
#                                                                                                 #
# MARIADB =  A better forked version of MySQL, it works precisely like MySQL with better          #
#            performance, better speed and tasks without the old-school MySQL post-processing.    #
#                                                                                                 #
# MONGODB =  MongoDB is a NoSQL system, that is based on querying Json files with a system        #
#            called Bson. Recommended to use since it is so much cleaner in terms of perfection.  #
#                                                                                                 #
# SQLITE =   SQLite is a system that does not need a connection to save data, instead is saves    #
#            data locally as per file per table, acting like a with no connection needed.         #
#                                                                                                 #
# FLATFILE = Flat File system is basically saving all your data inside either json or YML, which  #
#            was not tested in terms of performance, but is predicted to dictate memory which     #
#            could result in lag, memory leaks, and more issues that were not tested officially.  #
#-------------------------------------------------------------------------------------------------#
database:
  type: MYSQL
  host: "localhost"
  port: 2212
  username: "user"
  password: "password"
  table-prefix: ""

chat:
   locked: false
   clear-template:
      - "&5&l&m----------------------------"
      - ""
      - "&d&lChat has been cleared"
      - ""
      - "&5&l&m----------------------------"

punishments-lang:
    tempban-template:
       - "&cYou are temporarily banned from &6yourserver.example&c."
       - ""
       - "&7Expiry: &f%time%"
       - ""
       - "&7Reason: &f%reason%"
       - ""
       - "&7If you feel this punishment is unjustified, fill out a support ticket at &6www.yourwebsite.com."
       
    ban-template:
       - "&cYou are permanently banned from &6yourserver.example&c."
       - ""
       - "&7Reason: &f%reason%"
       - ""
       - "&7If you feel this punishment is unjustified, fill out a support ticket at &6www.yourwebsite.com."
        
    kick-template:
        - "&cYou have been kicked from &6yourserver.example&c."
        - ""
        - "&7Reason: &f%reason%"


report-lang:
  staff-template:
    - "&7&m-----&6&lNew Report&7&m-----"
    - "&7Reported: &c%REPORTED%"
    - "&7Reporter: &a%REPORTER%"
    - "&7Type: &e%TYPE%"
    - "&7Status: &e%STATUS%"
    - "&7&m---------------------"

reasons:
  fly-hacks:
    display-name: "Fly"
    lore:
    - "The player is flying&7."
    icon: FEATHER
  speed-hacks:
    display-name: "Speed"
    lore:
    - "The player is moving too quick&7."
    icon: CHAINMAIL_LEGGINGS
  force-field-hack:
    display-name: "ForceField"
    lore:
    - "The player is hitting players/entities abnormally&7."
    icon: IRON_SWORD
  reach-hacks:
    display-name: "Reach"
    lore:
    - "The player is hitting players/entities from far away&7."
    icon: STICK
  rapidbowshot-hack:
    display-name: "RapidBowShot"
    lore:
    - "The player is shooting arrows too quickly&7."
    icon: BOW
  noknockback-hack:
    display-name: "NoKnockback"
    lore:
    - "The player does not take any knock back&7."
    icon: FISHING_ROD
  grief:
    display-name: "Grief"
    lore:
    - "The player has griefed one of my constructions&7."
    icon: TNT
  chat-insults:
    display-name: "Insults"
    lore:
    - "The player is disrespectful&7."
    icon: OAK_SIGN