################################################################
#                                                              #
#          █▀▀ █▀█ █▀▄▀█ █▀▄▀█ ▄▀█ █▄ █ █▀▄ █▀ ▄█▄             #
#          █▄▄ █▄█ █ ▀ █ █ ▀ █ █▀█ █ ▀█ █▄▀ ▄█  ▀              #
#                                                              #
#█▄▄ █▄█   █▀▀ █▀▄ ▄▀█ █   █ ▄▀█   ▄▀ █▀█ █▀▀ █ █▀█ ▀█▀ █ █▀▄▀█#
#█▄█  █    █▄█ █▄▀ █▀█ █▄▄ █ █▀█ ▄▀   █▄█ █▀  █ █▀▄  █  █ █ ▀ █#
#                                                              #
################################################################

PREFIX: "&7Commands&b+ &f» "
ban-command: "ban {player} no alts online!"
kick-command: "kick {player} no alts online!"

#If you want to disable the welcome message just change to true.
disable_welcome_message: false

#If you want to disable the sounds just change to true.
disable_sounds: false

chat:
   locked: false
   clear-template:
      - "&5&l&m----------------------------"
      - ""
      - "&d&lChat has been cleared"
      - ""
      - "&5&l&m----------------------------"

punishments-lang:
    tempban-template:
       - "&cYou are temporarily banned from &6yourserver.example&c."
       - ""
       - "&7Expiry: &f%time%"
       - ""
       - "&7Reason: &f%reason%"
       - ""
       - "&7If you feel this punishment is unjustified, fill out a support ticket at &6www.yourwebsite.com."
       
    ban-template:
       - "&cYou are permanently banned from &6yourserver.example&c."
       - ""
       - "&7Reason: &f%reason%"
       - ""
       - "&7If you feel this punishment is unjustified, fill out a support ticket at &6www.yourwebsite.com."
        
    kick-template:
        - "&cYou have been kicked from &6yourserver.example&c."
        - ""
        - "&7Reason: &f%reason%"


report-lang:
  staff-template:
    - "&7&m-----&6&lNew Report&7&m-----"
    - "&7Reported: &c%REPORTED%"
    - "&7Reporter: &a%REPORTER%"
    - "&7Type: &e%TYPE%"
    - "&7Status: &e%STATUS%"
    - "&7&m---------------------"

# The maximum reasons is 27 and all the reasons title need to be like this for example 'Reason1 Reason2 etc..'
default-reasons:
  fly-hacks:
    Name: "Fly"
    Lore: "The player is flying&7."
    Item: "Feather"
  speed-hacks:
    Name: "Speed"
    Lore: "The player is moving too quick&7."
    Item: "Chainmail_leggings"
  force-field-hack:
    Name: "ForceField"
    Lore: "The player is hitting players/entities abnormally&7."
    Item: "Iron_sword"
  reach-hacks:
    Name: "Reach"
    Lore: "The player is hitting players/entities from far away&7."
    Item: "Stick"
  rapidbowshot-hack:
    Name: "RapidBowShot"
    Lore: "The player is shooting arrows quickly&7."
    Item: "Bow"
  noknockback-hack:
    Name: "NoKnockback"
    Lore: "The player isn't knocked back when he is hit&7."
    Item: "Fishing_rod"
  unknown_reason:
    Name: "???"
    Lore: "The player ??&7."
    Item: "Chest"
  grief:
    Name: "Grief"
    Lore: "The player griefed one of my construction&7."
    Item: "TNT"
  chat-insults:
    Name: "Insults"
    Lore: "The player is disrespectful&7."
    Item: "Oak_Sign"