name: CommandsPlus
main: dev.gdalia.commandsplus.Main
version: 1.0.4
api-version: 1.18
author: Gdalia, OfirTIM
commands:
  alts:
    description: Alts command.
  ban:
    description: Ban command.
  buildmode:
    description: Buildmode command.
  chat:
    description: Chat command.
  check:
    description: Check command.
  commandsplus:
    aliases: cp
    description: Commandsplus commnad.
  feed:
    description: Feed command.
  fly:
    description: Fly command.
  flyspeed:
    description: Flyspeed command.
  freeze:
    description: Freeze command.
  gamemode:
    aliases: gm
    description: Gamemode command.
  god:
    description: God command.
  heal:
    description: Heal command.
  history:
    description: History command.
  kick:
    description: Kick command.
  mute:
    description: Mute command.
  staffchat:
    aliases: sc
    description: Staffchat command.
  tempban:
    aliases: tban
    description: Tempban command.
  tempmute:
    aliases: tmute
    description: Tempmute command.
  time:
    description: Time command.
  tpall:
    description: Tpall command.
  tphere:
    description: Tphere command.
  unban:
    description: Unban command.
  unmute:
    description: Unmute command.
  vanish:
    description: Vanish command.
  warn:
    description: Warn command.
  report:
    description: Report command.
  reports:
    description: Reports command.